In [13]:
!pip install pandas scikit-learn tensorflow
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Resume.csv')
print(df.head())
tfidf = TfidfVectorizer(stop_words='english')
X = tfidf.fit_transform(df['resume_text'])  # Assuming 'resume_text' is the column with resume text


Saving Resume.csv to Resume (6).csv
         ID                                         Resume_str  \
0  16852973           HR ADMINISTRATOR/MARKETING ASSOCIATE\...   
1  22323967           HR SPECIALIST, US HR OPERATIONS      ...   
2  33176873           HR DIRECTOR       Summary      Over 2...   
3  27018550           HR SPECIALIST       Summary    Dedica...   
4  17812897           HR MANAGER         Skill Highlights  ...   

                                         Resume_html Category  
0  <div class="fontsize fontface vmargins hmargin...       HR  
1  <div class="fontsize fontface vmargins hmargin...       HR  
2  <div class="fontsize fontface vmargins hmargin...       HR  
3  <div class="fontsize fontface vmargins hmargin...       HR  
4  <div class="fontsize fontface vmargins hmargin...       HR  


KeyError: 'resume_text'

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

# Upload the file
uploaded = files.upload()

# Load the dataset
df = pd.read_csv('/content/Resume.csv')

# Print the actual column names to verify
print(df.columns)  # This will print the columns, make sure 'Resume_str' is present

# Preprocessing the text data using TF-IDF
tfidf = TfidfVectorizer(stop_words='english')
X = tfidf.fit_transform(df['Resume_str'])  # Use 'Resume_str' instead of 'Resume_Text'
print(X.shape)  # Print the shape of the transformed matrix

# Assuming 'Category' is your target variable (e.g., 'Qualified' or 'Not Qualified')
y = df['Category']  # Replace 'Category' with your actual label column

# Split data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define the models
models = {
    'Random Forest': RandomForestClassifier(),
    'Logistic Regression': LogisticRegression(),
    'SVM (Support Vector Machine)': SVC(),
    'KNN (K-Nearest Neighbors)': KNeighborsClassifier(),
    'Naive Bayes': MultinomialNB(),
    'Decision Tree': DecisionTreeClassifier()
}

# Train each model, predict on test set, and evaluate accuracy
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Print the result for this model
    print(f'{model_name} Accuracy: {accuracy:.4f}')


KeyboardInterrupt: 

In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from google.colab import files
import os

# Check if file exists, if not, prompt to upload
if not os.path.exists('/content/Resume.csv'):
    uploaded = files.upload()

# Load the dataset
df = pd.read_csv('/content/Resume.csv')

# Print the actual column names to verify
print(df.columns)  # This will print the columns, make sure 'Resume_str' is present

# Preprocessing the text data using TF-IDF
tfidf = TfidfVectorizer(stop_words='english')
X = tfidf.fit_transform(df['Resume_str'])  # Use 'Resume_str' instead of 'Resume_Text'
print(X.shape)  # Print the shape of the transformed matrix

# Assuming 'Category' is your target variable (e.g., 'Qualified' or 'Not Qualified')
y = df['Category']  # Replace 'Category' with your actual label column

# Split data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Importing the models for training
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Define the models
models = {
    'Random Forest': RandomForestClassifier(),
    'Logistic Regression': LogisticRegression(),
    'SVM (Support Vector Machine)': SVC(),
    'KNN (K-Nearest Neighbors)': KNeighborsClassifier(),
    'Naive Bayes': MultinomialNB(),
    'Decision Tree': DecisionTreeClassifier()
}

# Train each model, predict on test set, and evaluate accuracy
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Print the result for this model
    print(f'{model_name} Accuracy: {accuracy:.4f}')


Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')
(2484, 40236)
Random Forest Accuracy: 0.6217
Logistic Regression Accuracy: 0.6398
SVM (Support Vector Machine) Accuracy: 0.5976
KNN (K-Nearest Neighbors) Accuracy: 0.5131
Naive Bayes Accuracy: 0.5292
Decision Tree Accuracy: 0.5815


In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
import joblib
from google.colab import files
import os

# Upload the file (this will only happen once)
if not os.path.exists('/content/Resume.csv'):
    uploaded = files.upload()

# Load the dataset
df = pd.read_csv('/content/Resume.csv')

# Print the actual column names to verify
print(df.columns)  # This will print the columns, make sure 'Resume_str' is present

# Preprocessing the text data using TF-IDF (with bigrams)
tfidf = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))  # Using bigrams
X = tfidf.fit_transform(df['Resume_str'])  # Use 'Resume_str' as the column for resume text
print(X.shape)  # Print the shape of the transformed matrix

# Assuming 'Category' is your target variable (e.g., 'Qualified' or 'Not Qualified')
y = df['Category']  # Replace 'Category' with your actual label column

# Split data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the models
models = {
    'Random Forest': RandomForestClassifier(),
    'Logistic Regression': LogisticRegression(),
    'SVM (Support Vector Machine)': SVC(),
    'KNN (K-Nearest Neighbors)': KNeighborsClassifier(),
    'Naive Bayes': MultinomialNB(),
    'Decision Tree': DecisionTreeClassifier()
}

# Train each model, predict on the test set, and evaluate accuracy
for model_name, model in models.items():
    print(f"\nTraining {model_name}...")

    # Hyperparameter tuning for Random Forest (example)
    if model_name == 'Random Forest':
        param_grid = {
            'n_estimators': [50, 100, 200],
            'max_depth': [10, 20, 30],
            'min_samples_split': [2, 5, 10]
        }
        grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='accuracy')
        grid_search.fit(X_train, y_train)
        best_model = grid_search.best_estimator_
        print(f"Best parameters for {model_name}: {grid_search.best_params_}")
        model = best_model  # Update to the best model found by GridSearchCV

    # Train the model
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Print the result for this model
    print(f'{model_name} Accuracy: {accuracy:.4f}')

    # Confusion Matrix
    print(f"Confusion Matrix for {model_name}:")
    print(confusion_matrix(y_test, y_pred))

    # Classification Report
    print(f"Classification Report for {model_name}:")
    print(classification_report(y_test, y_pred))

    # Cross-validation scores
    cv_scores = cross_val_score(model, X, y, cv=5)
    print(f"Cross-Validation Scores for {model_name}: {cv_scores}")
    print(f"Mean CV Score for {model_name}: {cv_scores.mean():.4f}")
    print(f"Standard Deviation of CV Score for {model_name}: {cv_scores.std():.4f}")

# Save the best model (you can replace 'Random Forest' with the top-performing model)
best_model = models['Logistic Regression']  # Replace with the top-performing model name
joblib.dump(best_model, 'resume_screener_model.pkl')
print("Best model saved as 'resume_screener_model.pkl'")


Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')
(2484, 724949)

Training Random Forest...
Best parameters for Random Forest: {'max_depth': 20, 'min_samples_split': 10, 'n_estimators': 200}
Random Forest Accuracy: 0.6117
Confusion Matrix for Random Forest:
[[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0 16  0  0  0  0  0  1  0  0  0  0  0  0  1  0  0  0  4  2  1  1  0  4]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  1  1  1  1  0  0  1  0  2]
 [ 0  1  0  5  0  0  0  1  0  0  0  0  0  2  1  3  0  2  1  0  0  0  2  2]
 [ 1  0  0  0  2  0  0  1  0  0  1  0  1  1  0  1  1  0  0  1  2  0  1  5]
 [ 0  1  0  0  0  0  2  0  0  0  0  0  0  0  0  1  0  1  1  0  0  0  0  0]
 [ 0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  2  0  1  0  0  3  0  0  0]
 [ 1  0  0  0  0  0  1 13  0  0  0  0  0  0  0  0  4  0  0  1  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  1  0 19  0  0  0  0  0

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Cross-Validation Scores for Random Forest: [0.6498994  0.64587525 0.62374245 0.59356137 0.54435484]
Mean CV Score for Random Forest: 0.6115
Standard Deviation of CV Score for Random Forest: 0.0391

Training Logistic Regression...
Logistic Regression Accuracy: 0.6258
Confusion Matrix for Logistic Regression:
[[24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  1  0  0  0  0  0]
 [ 0 15  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  9  1  1  1  1  1]
 [ 1  0  1  0  0  0  0  0  0  1  0  0  1  0  0  1  0  0  0  0  0  0  1  2]
 [ 0  1  0  6  2  0  0  1  0  0  0  0  0  2  0  2  0  0  0  0  0  0  5  1]
 [ 0  0  0  1  0  0  0  0  0  0  1  0  1  1  0  1  2  0  0  1  2  0  1  7]
 [ 0  4  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  2  0  0  0  0  1  0  0  0]
 [ 1  0  0  0  1  0  0 15  0  0  0  0  1  0  0  1  3  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1  0  0  0]
 [ 0  0  0  0  0

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Cross-Validation Scores for Logistic Regression: [0.67806841 0.63782696 0.62374245 0.61569416 0.56451613]
Mean CV Score for Logistic Regression: 0.6240
Standard Deviation of CV Score for Logistic Regression: 0.0367

Training SVM (Support Vector Machine)...
SVM (Support Vector Machine) Accuracy: 0.5755
Confusion Matrix for SVM (Support Vector Machine):
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  1  0  0  0  0  0]
 [ 0 16  0  0  1  0  0  0  0  0  0  0  2  0  0  0  0  0 10  0  0  0  1  0]
 [ 1  0  0  0  0  0  0  0  0  1  0  0  2  0  0  1  0  0  0  0  0  0  1  2]
 [ 0  3  0  4  2  0  1  0  0  0  0  0  2  1  0  0  0  0  0  0  0  0  7  0]
 [ 0  1  0  0  3  0  0  0  0  0  0  0  3  1  0  0  1  0  0  1  2  0  3  3]
 [ 0  3  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 18  0  0  0  0  0  1  0  0  1  0  0  0  0  1  0  0  0]
 [ 1  0  0  0  1  0  0 15  0  0  0  0  5  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Cross-Validation Scores for SVM (Support Vector Machine): [0.61770624 0.62173038 0.56740443 0.57947686 0.52217742]
Mean CV Score for SVM (Support Vector Machine): 0.5817
Standard Deviation of CV Score for SVM (Support Vector Machine): 0.0365

Training KNN (K-Nearest Neighbors)...
KNN (K-Nearest Neighbors) Accuracy: 0.4869
Confusion Matrix for KNN (K-Nearest Neighbors):
[[24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  1  0  0  0  0  0]
 [ 2 11  1  1  3  0  0  0  0  1  0  0  0  0  1  0  0  0  7  1  0  1  0  1]
 [ 1  1  1  0  1  0  0  0  0  1  0  0  1  0  0  1  0  0  0  0  0  0  0  1]
 [ 1  3  0  6  1  1  0  1  0  2  0  0  0  1  1  2  0  0  0  0  0  0  0  1]
 [ 0  3  0  0  3  0  0  0  1  1  0  0  0  2  0  0  0  0  0  2  0  0  2  4]
 [ 0  2  0  1  0  1  1  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 1  1  0  1  0  1 11  1  0  1  0  0  0  0  0  1  0  0  0  0  3  0  0  0]
 [ 3  1  0  0  0  0  0 14  1  3  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  1  0  0

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Cross-Validation Scores for Naive Bayes: [0.5694165  0.5472837  0.5472837  0.50704225 0.46774194]
Mean CV Score for Naive Bayes: 0.5278
Standard Deviation of CV Score for Naive Bayes: 0.0361

Training Decision Tree...
Decision Tree Accuracy: 0.6016
Confusion Matrix for Decision Tree:
[[21  0  0  2  0  3  0  0  0  0  0  0  0  1  0  0  1  0  0  1  0  0  0  0]
 [ 0 23  0  1  1  0  0  0  0  1  1  0  0  0  0  0  0  1  0  1  0  0  0  1]
 [ 0  0  4  0  0  0  0  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  5  1  0  0  2  0  0  2  1  1  2  0  0  0  0  0  0  1  2  1  2]
 [ 0  0  0  1  9  0  0  0  0  1  0  0  0  1  0  0  0  0  0  1  1  1  2  1]
 [ 0  0  1  1  2  1  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  1 12  0  2  0  0  1  0  0  0  2  1  0  0  1  1  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  1  0  3  0  0  0  2  2 12  0  0  0

In [19]:
# Initialize a dictionary to store the evaluation results
model_performance = {}

# Train and evaluate each model
for model_name, model in models.items():
    print(f"\nTraining {model_name}...")

    # Hyperparameter tuning for Random Forest (example)
    if model_name == 'Random Forest':
        param_grid = {
            'n_estimators': [50, 100, 200],
            'max_depth': [10, 20, 30],
            'min_samples_split': [2, 5, 10]
        }
        grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='accuracy')
        grid_search.fit(X_train, y_train)
        best_model = grid_search.best_estimator_
        print(f"Best parameters for {model_name}: {grid_search.best_params_}")
        model = best_model  # Update to the best model found by GridSearchCV

    # Train the model
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Confusion Matrix
    conf_matrix = confusion_matrix(y_test, y_pred)

    # Classification Report
    class_report = classification_report(y_test, y_pred, output_dict=True)

    # Cross-validation scores
    cv_scores = cross_val_score(model, X, y, cv=5)

    # Store the results
    model_performance[model_name] = {
        'accuracy': accuracy,
        'confusion_matrix': conf_matrix,
        'classification_report': class_report,
        'cv_mean': cv_scores.mean(),
        'cv_std': cv_scores.std()
    }

# Now compare the performance of all models
for model_name, performance in model_performance.items():
    print(f"\n{model_name} Performance:")
    print(f"Accuracy: {performance['accuracy']:.4f}")
    print(f"Cross-Validation Mean Score: {performance['cv_mean']:.4f}")
    print(f"Cross-Validation Std Dev: {performance['cv_std']:.4f}")
    print(f"Confusion Matrix:\n{performance['confusion_matrix']}")
    print(f"Classification Report:\n{performance['classification_report']}")

# Find the model with the highest accuracy
best_model_name = max(model_performance, key=lambda x: model_performance[x]['accuracy'])
print(f"\nBest Model Based on Accuracy: {best_model_name}")



Training Random Forest...
Best parameters for Random Forest: {'max_depth': 20, 'min_samples_split': 2, 'n_estimators': 200}


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Training Logistic Regression...


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Training SVM (Support Vector Machine)...


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Training KNN (K-Nearest Neighbors)...

Training Naive Bayes...


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Training Decision Tree...

Random Forest Performance:
Accuracy: 0.6237
Cross-Validation Mean Score: 0.6119
Cross-Validation Std Dev: 0.0368
Confusion Matrix:
[[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 1 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  2  2  1  2  5]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  1  0  0  0  1  1  2]
 [ 0  0  0  4  2  0  0  0  0  1  0  0  0  2  0  3  0  1  0  0  1  0  5  1]
 [ 0  0  0  0  1  0  0  1  0  0  1  0  0  1  0  1  1  0  0  2  1  1  1  7]
 [ 0  2  0  0  0  0  2  1  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0]
 [ 1  0  0  0  0  0  0 13  0  1  0  0  0  0  0  1  3  0  0  1  3  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  1  0 21  0  0  0  0  0  0  1  0  1  2  0  0  1  0]
 [ 0  0  0  0  0  0  2  0  0  0 18  0  0  0  0  0  0  1  2  0  0  0  0  1]
 [ 0  0  0  0  1

In [20]:
import joblib

# Save the best model
joblib.dump(models['Logistic Regression'], 'resume_screener_model.pkl')
print("Best model (Logistic Regression) saved as 'resume_screener_model.pkl'")

# Save the TF-IDF Vectorizer as well
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')
print("TF-IDF Vectorizer saved as 'tfidf_vectorizer.pkl'")


Best model (Logistic Regression) saved as 'resume_screener_model.pkl'
TF-IDF Vectorizer saved as 'tfidf_vectorizer.pkl'


In [21]:
# Load the trained model and vectorizer
loaded_model = joblib.load('resume_screener_model.pkl')
loaded_vectorizer = joblib.load('tfidf_vectorizer.pkl')


In [23]:
def predict_resume_category(resume_text):
    # Transform the resume text using the loaded TF-IDF vectorizer
    resume_tfidf = loaded_vectorizer.transform([resume_text])

    # Predict category
    predicted_category = loaded_model.predict(resume_tfidf)

    return predicted_category[0]


In [26]:
sample_resume = "Experienced AI engineer skilled in deep learning and NLP. Developed multiple ML models for classification tasks."
predicted_category = predict_resume_category(sample_resume)
print(f"Predicted Category: {predicted_category}")


Predicted Category: ENGINEERING
